// service: opentelemetry/proto/collector/logs/v1/logs_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var opentelemetry_proto_logs_v1_logs_pb = require('../../../../../opentelemetry/proto/logs/v1/logs_pb.js');
goog.object.extend(proto, opentelemetry_proto_logs_v1_logs_pb);
goog.exportSymbol('proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess', null, global);
goog.exportSymbol('proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest', null, global);
goog.exportSymbol('proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.repeatedFields_, null);
};
goog.inherits(proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.displayName = 'proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.displayName = 'proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.displayName = 'proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceLogsList: jspb.Message.toObjectList(msg.getResourceLogsList(),
    opentelemetry_proto_logs_v1_logs_pb.ResourceLogs.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest;
  return proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new opentelemetry_proto_logs_v1_logs_pb.ResourceLogs;
      reader.readMessage(value,opentelemetry_proto_logs_v1_logs_pb.ResourceLogs.deserializeBinaryFromReader);
      msg.addResourceLogs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResourceLogsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      opentelemetry_proto_logs_v1_logs_pb.ResourceLogs.serializeBinaryToWriter
    );
  }
};


/**
 * repeated opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1;
 * @return {!Array<!proto.opentelemetry.proto.logs.v1.ResourceLogs>}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.prototype.getResourceLogsList = function() {
  return /** @type{!Array<!proto.opentelemetry.proto.logs.v1.ResourceLogs>} */ (
    jspb.Message.getRepeatedWrapperField(this, opentelemetry_proto_logs_v1_logs_pb.ResourceLogs, 1));
};


/**
 * @param {!Array<!proto.opentelemetry.proto.logs.v1.ResourceLogs>} value
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest} returns this
*/
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.prototype.setResourceLogsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.opentelemetry.proto.logs.v1.ResourceLogs=} opt_value
 * @param {number=} opt_index
 * @return {!proto.opentelemetry.proto.logs.v1.ResourceLogs}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.prototype.addResourceLogs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.opentelemetry.proto.logs.v1.ResourceLogs, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest} returns this
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest.prototype.clearResourceLogsList = function() {
  return this.setResourceLogsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    partialSuccess: (f = msg.getPartialSuccess()) && proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse;
  return proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess;
      reader.readMessage(value,proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.deserializeBinaryFromReader);
      msg.setPartialSuccess(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPartialSuccess();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.serializeBinaryToWriter
    );
  }
};


/**
 * optional ExportLogsPartialSuccess partial_success = 1;
 * @return {?proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.prototype.getPartialSuccess = function() {
  return /** @type{?proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess} */ (
    jspb.Message.getWrapperField(this, proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess, 1));
};


/**
 * @param {?proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess|undefined} value
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse} returns this
*/
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.prototype.setPartialSuccess = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse} returns this
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.prototype.clearPartialSuccess = function() {
  return this.setPartialSuccess(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse.prototype.hasPartialSuccess = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.prototype.toObject = function(opt_includeInstance) {
  return proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.toObject = function(includeInstance, msg) {
  var f, obj = {
    rejectedLogRecords: jspb.Message.getFieldWithDefault(msg, 1, 0),
    errorMessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess;
  return proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRejectedLogRecords(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRejectedLogRecords();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int64 rejected_log_records = 1;
 * @return {number}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.prototype.getRejectedLogRecords = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess} returns this
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.prototype.setRejectedLogRecords = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string error_message = 2;
 * @return {string}
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess} returns this
 */
proto.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccess.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.opentelemetry.proto.collector.logs.v1);
