/**
 * @fileoverview gRPC-Web generated client stub for opentelemetry.proto.collector.trace.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0
// source: opentelemetry/proto/collector/trace/v1/trace_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var opentelemetry_proto_trace_v1_trace_pb = require('../../../../../opentelemetry/proto/trace/v1/trace_pb.js')
const proto = {};
proto.opentelemetry = {};
proto.opentelemetry.proto = {};
proto.opentelemetry.proto.collector = {};
proto.opentelemetry.proto.collector.trace = {};
proto.opentelemetry.proto.collector.trace.v1 = require('./trace_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.opentelemetry.proto.collector.trace.v1.TraceServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.opentelemetry.proto.collector.trace.v1.TraceServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest,
 *   !proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse>}
 */
const methodDescriptor_TraceService_Export = new grpc.web.MethodDescriptor(
  '/opentelemetry.proto.collector.trace.v1.TraceService/Export',
  grpc.web.MethodType.UNARY,
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest,
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse,
  /**
   * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.deserializeBinary
);


/**
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.opentelemetry.proto.collector.trace.v1.TraceServiceClient.prototype.export =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/opentelemetry.proto.collector.trace.v1.TraceService/Export',
      request,
      metadata || {},
      methodDescriptor_TraceService_Export,
      callback);
};


/**
 * @param {!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse>}
 *     Promise that resolves to the response
 */
proto.opentelemetry.proto.collector.trace.v1.TraceServicePromiseClient.prototype.export =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/opentelemetry.proto.collector.trace.v1.TraceService/Export',
      request,
      metadata || {},
      methodDescriptor_TraceService_Export);
};


module.exports = proto.opentelemetry.proto.collector.trace.v1;

